### ISSUE TITLE
Players having issues with higher tiers [1.18.1 fabric]

### ISSUE THREAD

**Issue by itsdinkd** [Tfarcenim/DankStorageFabric#59]
This is the 5th report from players of AQM2 saying that once they hit a certain tier they are shown a message about not being able to open the tier lower than the one they have.
![image](https://user-images.githubusercontent.com/35115304/147856988-e17bb7dd-fb22-4ed6-a3dd-3d50f3a94ac5.png)

they are forced to use a dock to get their stuff out and the dank is completely broken and cannot be opened otherwise.

**Comment by Tfarcenim** [comment]
Is this on a world that used older versions of dank storage?  There are some known issues that were in older versions that caused inventory corruption.

The problem is, newer versions on existing worlds with older versions of dank storage will still be broken, but I've added some commands to help with that.

What's interesting is they somehow have a dank that's higher level than the inventory that backs it, which is no longer possible in survival on the newer versions.  (Upgrading a dank on newer version can only upgrade the backing inventory, it cannot downgrade)

*The survival friendly workaround here is can be fixed by upgrading the dank again (to level 7) or changing a dank 5 to that id and upgrading that to level 6.*

I'll add some commands for manually setting inventory levels to help with fixing existing worlds, once this is done the issue will be closed.

**Comment by Tfarcenim** [comment]
Fyi, not being able to open a backing inventory with danks of unequal tier is **not a bug.**

It is both crash prevention and an exploit fix.

Really the only thing I'm doing here is providing a way to fix older worlds.

**Comment by itsdinkd** [comment]
> Fyi, not being able to open a backing inventory with danks of unequal tier is **not a bug.**
> 
> It is both crash prevention and an exploit fix.
> 
> Really the only thing I'm doing here is providing a way to fix older worlds.

They are trying to open their tier 7 for example, and its saying they cannot open a tier 6.. while they have a tier 7.. 


As for the world, I don't know, this is in my modpack and people are reporting it to me from their own servers.

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/147860017-79fc963b-962a-4790-87d3-d788ef67704d.png)

Here is what someone said about what I was talking about in my last comment

**Comment by Tfarcenim** [comment]
Since there's no details how to reproduce it and I can't get a straight answer on whether it was a pre-existing world or not, I'll give the tools they need to fix it on their own, and after that it's not my problem(tm).

**Comment by itsdinkd** [comment]
Your mod has been in my modpack since 1.18.1 released so I would imagine its happening on pre-existing worlds.

**Comment by Tfarcenim** [comment]
`/dankstorage set_tier <id> <tier>` will fix the mismatched danks.

**Comment by itsdinkd** [comment]
The command is counter intuitive and non-technical people running servers are not going to know how to get the ID of a dank..... Requiring people to go into a dat file with NBTExplorer is no solution.

/dankstorage set_tier

in order for this to make sense, you would have to add a command to pull in the ID for the current dank they are holding in their hand. The player then would tell the OP the ID in question, or allow targeting people with the command to fetch all the targets current danks with tier and id attached.
/dankstorage get_id

**Comment by itsdinkd** [comment]
Command does not work.

 Tried /dankstorage set_tier 24 6 
 
 console returned: [04:45:37] [Server thread/INFO] (MinecraftServer) Integer must not be more than 7, found 24

so then I figured okay.... it must be backwards, so I swapped 24 with 6 and visa versa. and then I got 

[04:45:50] [Server thread/INFO] (MinecraftServer) An unexpected error occurred trying to execute that command
